/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProfileApiKeysRouteImport } from './routes/_authenticated/profile/api-keys'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminPluginsIndexRouteImport } from './routes/_authenticated/admin/plugins/index'
import { Route as AuthenticatedAdminGlobalRolesIndexRouteImport } from './routes/_authenticated/admin/global-roles/index'
import { Route as AuthenticatedProjectsProjectIdTeamIndexRouteImport } from './routes/_authenticated/projects/$projectId/team/index'
import { Route as AuthenticatedProjectsProjectIdSettingsIndexRouteImport } from './routes/_authenticated/projects/$projectId/settings/index'
import { Route as AuthenticatedProjectsProjectIdDocsIndexRouteImport } from './routes/_authenticated/projects/$projectId/docs/index'
import { Route as AuthenticatedProjectsProjectIdAutomationIndexRouteImport } from './routes/_authenticated/projects/$projectId/automation/index'
import { Route as AuthenticatedProjectsProjectIdAgentsIndexRouteImport } from './routes/_authenticated/projects/$projectId/agents/index'
import { Route as AuthenticatedProjectsProjectIdTasksTaskIdRouteImport } from './routes/_authenticated/projects/$projectId/tasks/$taskId'
import { Route as AuthenticatedProjectsProjectIdInteractionsTimelineRouteImport } from './routes/_authenticated/projects/$projectId/interactions/timeline'
import { Route as AuthenticatedProjectsProjectIdInteractionsBacklogRouteImport } from './routes/_authenticated/projects/$projectId/interactions/backlog'
import { Route as AuthenticatedProjectsProjectIdDocsDocIdRouteImport } from './routes/_authenticated/projects/$projectId/docs/$docId'
import { Route as AuthenticatedProjectsProjectIdConversationsConversationIdRouteImport } from './routes/_authenticated/projects/$projectId/conversations/$conversationId'
import { Route as AuthenticatedProjectsProjectIdAutomationWorkflowIdRouteImport } from './routes/_authenticated/projects/$projectId/automation/$workflowId'
import { Route as AuthenticatedAdminPluginsPluginIdSlugRouteImport } from './routes/_authenticated/admin/plugins/$pluginId/$slug'
import { Route as AuthenticatedProjectsProjectIdAgentsAgentIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/agents/$agentId/index'
import { Route as AuthenticatedProjectsProjectIdPluginsPluginIdSlugRouteImport } from './routes/_authenticated/projects/$projectId/plugins/$pluginId/$slug'
import { Route as AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRouteImport } from './routes/_authenticated/projects/$projectId/interactions/sprints/$sprintId'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileApiKeysRoute =
  AuthenticatedProfileApiKeysRouteImport.update({
    id: '/profile/api-keys',
    path: '/profile/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPluginsIndexRoute =
  AuthenticatedAdminPluginsIndexRouteImport.update({
    id: '/admin/plugins/',
    path: '/admin/plugins/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGlobalRolesIndexRoute =
  AuthenticatedAdminGlobalRolesIndexRouteImport.update({
    id: '/admin/global-roles/',
    path: '/admin/global-roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdTeamIndexRoute =
  AuthenticatedProjectsProjectIdTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsIndexRoute =
  AuthenticatedProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocsIndexRoute =
  AuthenticatedProjectsProjectIdDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAutomationIndexRoute =
  AuthenticatedProjectsProjectIdAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAgentsIndexRoute =
  AuthenticatedProjectsProjectIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksTaskIdRoute =
  AuthenticatedProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInteractionsTimelineRoute =
  AuthenticatedProjectsProjectIdInteractionsTimelineRouteImport.update({
    id: '/interactions/timeline',
    path: '/interactions/timeline',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInteractionsBacklogRoute =
  AuthenticatedProjectsProjectIdInteractionsBacklogRouteImport.update({
    id: '/interactions/backlog',
    path: '/interactions/backlog',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocsDocIdRoute =
  AuthenticatedProjectsProjectIdDocsDocIdRouteImport.update({
    id: '/docs/$docId',
    path: '/docs/$docId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdConversationsConversationIdRoute =
  AuthenticatedProjectsProjectIdConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute =
  AuthenticatedProjectsProjectIdAutomationWorkflowIdRouteImport.update({
    id: '/automation/$workflowId',
    path: '/automation/$workflowId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminPluginsPluginIdSlugRoute =
  AuthenticatedAdminPluginsPluginIdSlugRouteImport.update({
    id: '/admin/plugins/$pluginId/$slug',
    path: '/admin/plugins/$pluginId/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute =
  AuthenticatedProjectsProjectIdAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute =
  AuthenticatedProjectsProjectIdPluginsPluginIdSlugRouteImport.update({
    id: '/plugins/$pluginId/$slug',
    path: '/plugins/$pluginId/$slug',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute =
  AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRouteImport.update({
    id: '/interactions/sprints/$sprintId',
    path: '/interactions/sprints/$sprintId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/profile/api-keys': typeof AuthenticatedProfileApiKeysRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/global-roles/': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/admin/plugins/': typeof AuthenticatedAdminPluginsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/admin/plugins/$pluginId/$slug': typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  '/projects/$projectId/automation/$workflowId': typeof AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute
  '/projects/$projectId/conversations/$conversationId': typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/docs/$docId': typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  '/projects/$projectId/interactions/backlog': typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  '/projects/$projectId/interactions/timeline': typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  '/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/agents/': typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/automation/': typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  '/projects/$projectId/docs/': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/settings/': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/team/': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/projects/$projectId/interactions/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  '/projects/$projectId/plugins/$pluginId/$slug': typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  '/projects/$projectId/agents/$agentId/': typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/profile/api-keys': typeof AuthenticatedProfileApiKeysRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/global-roles': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/admin/plugins': typeof AuthenticatedAdminPluginsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/admin/plugins/$pluginId/$slug': typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  '/projects/$projectId/automation/$workflowId': typeof AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute
  '/projects/$projectId/conversations/$conversationId': typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/docs/$docId': typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  '/projects/$projectId/interactions/backlog': typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  '/projects/$projectId/interactions/timeline': typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  '/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/agents': typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/automation': typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  '/projects/$projectId/docs': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/team': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/projects/$projectId/interactions/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  '/projects/$projectId/plugins/$pluginId/$slug': typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  '/projects/$projectId/agents/$agentId': typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/_authenticated/profile/api-keys': typeof AuthenticatedProfileApiKeysRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin/global-roles/': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/_authenticated/admin/plugins/': typeof AuthenticatedAdminPluginsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/admin/plugins/$pluginId/$slug': typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  '/_authenticated/projects/$projectId/automation/$workflowId': typeof AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute
  '/_authenticated/projects/$projectId/conversations/$conversationId': typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  '/_authenticated/projects/$projectId/docs/$docId': typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  '/_authenticated/projects/$projectId/interactions/backlog': typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  '/_authenticated/projects/$projectId/interactions/timeline': typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  '/_authenticated/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/_authenticated/projects/$projectId/agents/': typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  '/_authenticated/projects/$projectId/automation/': typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  '/_authenticated/projects/$projectId/docs/': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/_authenticated/projects/$projectId/settings/': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/_authenticated/projects/$projectId/team/': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/_authenticated/projects/$projectId/interactions/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  '/_authenticated/projects/$projectId/plugins/$pluginId/$slug': typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  '/_authenticated/projects/$projectId/agents/$agentId/': typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/profile/api-keys'
    | '/projects/$projectId'
    | '/home/'
    | '/profile/'
    | '/admin/global-roles/'
    | '/admin/plugins/'
    | '/admin/users/'
    | '/projects/$projectId/'
    | '/admin/plugins/$pluginId/$slug'
    | '/projects/$projectId/automation/$workflowId'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/docs/$docId'
    | '/projects/$projectId/interactions/backlog'
    | '/projects/$projectId/interactions/timeline'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/agents/'
    | '/projects/$projectId/automation/'
    | '/projects/$projectId/docs/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/team/'
    | '/projects/$projectId/interactions/sprints/$sprintId'
    | '/projects/$projectId/plugins/$pluginId/$slug'
    | '/projects/$projectId/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/profile/api-keys'
    | '/home'
    | '/profile'
    | '/admin/global-roles'
    | '/admin/plugins'
    | '/admin/users'
    | '/projects/$projectId'
    | '/admin/plugins/$pluginId/$slug'
    | '/projects/$projectId/automation/$workflowId'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/docs/$docId'
    | '/projects/$projectId/interactions/backlog'
    | '/projects/$projectId/interactions/timeline'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/automation'
    | '/projects/$projectId/docs'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/team'
    | '/projects/$projectId/interactions/sprints/$sprintId'
    | '/projects/$projectId/plugins/$pluginId/$slug'
    | '/projects/$projectId/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/_authenticated/profile/api-keys'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/home/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin/global-roles/'
    | '/_authenticated/admin/plugins/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/admin/plugins/$pluginId/$slug'
    | '/_authenticated/projects/$projectId/automation/$workflowId'
    | '/_authenticated/projects/$projectId/conversations/$conversationId'
    | '/_authenticated/projects/$projectId/docs/$docId'
    | '/_authenticated/projects/$projectId/interactions/backlog'
    | '/_authenticated/projects/$projectId/interactions/timeline'
    | '/_authenticated/projects/$projectId/tasks/$taskId'
    | '/_authenticated/projects/$projectId/agents/'
    | '/_authenticated/projects/$projectId/automation/'
    | '/_authenticated/projects/$projectId/docs/'
    | '/_authenticated/projects/$projectId/settings/'
    | '/_authenticated/projects/$projectId/team/'
    | '/_authenticated/projects/$projectId/interactions/sprints/$sprintId'
    | '/_authenticated/projects/$projectId/plugins/$pluginId/$slug'
    | '/_authenticated/projects/$projectId/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/api-keys': {
      id: '/_authenticated/profile/api-keys'
      path: '/profile/api-keys'
      fullPath: '/profile/api-keys'
      preLoaderRoute: typeof AuthenticatedProfileApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/plugins/': {
      id: '/_authenticated/admin/plugins/'
      path: '/admin/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AuthenticatedAdminPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/global-roles/': {
      id: '/_authenticated/admin/global-roles/'
      path: '/admin/global-roles'
      fullPath: '/admin/global-roles/'
      preLoaderRoute: typeof AuthenticatedAdminGlobalRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/team/': {
      id: '/_authenticated/projects/$projectId/team/'
      path: '/team'
      fullPath: '/projects/$projectId/team/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTeamIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings/': {
      id: '/_authenticated/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/docs/': {
      id: '/_authenticated/projects/$projectId/docs/'
      path: '/docs'
      fullPath: '/projects/$projectId/docs/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/automation/': {
      id: '/_authenticated/projects/$projectId/automation/'
      path: '/automation'
      fullPath: '/projects/$projectId/automation/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/agents/': {
      id: '/_authenticated/projects/$projectId/agents/'
      path: '/agents'
      fullPath: '/projects/$projectId/agents/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks/$taskId': {
      id: '/_authenticated/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interactions/timeline': {
      id: '/_authenticated/projects/$projectId/interactions/timeline'
      path: '/interactions/timeline'
      fullPath: '/projects/$projectId/interactions/timeline'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInteractionsTimelineRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interactions/backlog': {
      id: '/_authenticated/projects/$projectId/interactions/backlog'
      path: '/interactions/backlog'
      fullPath: '/projects/$projectId/interactions/backlog'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInteractionsBacklogRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/docs/$docId': {
      id: '/_authenticated/projects/$projectId/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/projects/$projectId/docs/$docId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocsDocIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/conversations/$conversationId': {
      id: '/_authenticated/projects/$projectId/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/projects/$projectId/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/automation/$workflowId': {
      id: '/_authenticated/projects/$projectId/automation/$workflowId'
      path: '/automation/$workflowId'
      fullPath: '/projects/$projectId/automation/$workflowId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAutomationWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/plugins/$pluginId/$slug': {
      id: '/_authenticated/admin/plugins/$pluginId/$slug'
      path: '/admin/plugins/$pluginId/$slug'
      fullPath: '/admin/plugins/$pluginId/$slug'
      preLoaderRoute: typeof AuthenticatedAdminPluginsPluginIdSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/agents/$agentId/': {
      id: '/_authenticated/projects/$projectId/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/projects/$projectId/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/plugins/$pluginId/$slug': {
      id: '/_authenticated/projects/$projectId/plugins/$pluginId/$slug'
      path: '/plugins/$pluginId/$slug'
      fullPath: '/projects/$projectId/plugins/$pluginId/$slug'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interactions/sprints/$sprintId': {
      id: '/_authenticated/projects/$projectId/interactions/sprints/$sprintId'
      path: '/interactions/sprints/$sprintId'
      fullPath: '/projects/$projectId/interactions/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute: typeof AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute
  AuthenticatedProjectsProjectIdConversationsConversationIdRoute: typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  AuthenticatedProjectsProjectIdDocsDocIdRoute: typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  AuthenticatedProjectsProjectIdInteractionsBacklogRoute: typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  AuthenticatedProjectsProjectIdInteractionsTimelineRoute: typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  AuthenticatedProjectsProjectIdTasksTaskIdRoute: typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  AuthenticatedProjectsProjectIdAgentsIndexRoute: typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  AuthenticatedProjectsProjectIdAutomationIndexRoute: typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  AuthenticatedProjectsProjectIdDocsIndexRoute: typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  AuthenticatedProjectsProjectIdSettingsIndexRoute: typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  AuthenticatedProjectsProjectIdTeamIndexRoute: typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute: typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute: typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute: typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute:
      AuthenticatedProjectsProjectIdAutomationWorkflowIdRoute,
    AuthenticatedProjectsProjectIdConversationsConversationIdRoute:
      AuthenticatedProjectsProjectIdConversationsConversationIdRoute,
    AuthenticatedProjectsProjectIdDocsDocIdRoute:
      AuthenticatedProjectsProjectIdDocsDocIdRoute,
    AuthenticatedProjectsProjectIdInteractionsBacklogRoute:
      AuthenticatedProjectsProjectIdInteractionsBacklogRoute,
    AuthenticatedProjectsProjectIdInteractionsTimelineRoute:
      AuthenticatedProjectsProjectIdInteractionsTimelineRoute,
    AuthenticatedProjectsProjectIdTasksTaskIdRoute:
      AuthenticatedProjectsProjectIdTasksTaskIdRoute,
    AuthenticatedProjectsProjectIdAgentsIndexRoute:
      AuthenticatedProjectsProjectIdAgentsIndexRoute,
    AuthenticatedProjectsProjectIdAutomationIndexRoute:
      AuthenticatedProjectsProjectIdAutomationIndexRoute,
    AuthenticatedProjectsProjectIdDocsIndexRoute:
      AuthenticatedProjectsProjectIdDocsIndexRoute,
    AuthenticatedProjectsProjectIdSettingsIndexRoute:
      AuthenticatedProjectsProjectIdSettingsIndexRoute,
    AuthenticatedProjectsProjectIdTeamIndexRoute:
      AuthenticatedProjectsProjectIdTeamIndexRoute,
    AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute:
      AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute,
    AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute:
      AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute,
    AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute:
      AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileApiKeysRoute: typeof AuthenticatedProfileApiKeysRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedAdminGlobalRolesIndexRoute: typeof AuthenticatedAdminGlobalRolesIndexRoute
  AuthenticatedAdminPluginsIndexRoute: typeof AuthenticatedAdminPluginsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminPluginsPluginIdSlugRoute: typeof AuthenticatedAdminPluginsPluginIdSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileApiKeysRoute: AuthenticatedProfileApiKeysRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedAdminGlobalRolesIndexRoute:
    AuthenticatedAdminGlobalRolesIndexRoute,
  AuthenticatedAdminPluginsIndexRoute: AuthenticatedAdminPluginsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedAdminPluginsPluginIdSlugRoute:
    AuthenticatedAdminPluginsPluginIdSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
